name: "Terraform Lifecycle"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  # -------------------------------------------------
  # Detect changed Terraform modules
  # -------------------------------------------------
  module-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed modules
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            random_pet:
              - 'tf-resouces/random_pet/**'
            random_password:
              - 'tf-resouces/random_password/**'

      - name: Create matrix from changes
        id: set-matrix
        run: |
          modules=()

          if [[ "${{ steps.filter.outputs.random_pet }}" == "true" ]]; then
            modules+=("\"random_pet\"")
          fi

          if [[ "${{ steps.filter.outputs.random_password }}" == "true" ]]; then
            modules+=("\"random_password\"")
          fi 

          if [ ${#modules[@]} -eq 0 ]; then
          matrix="[]"
          else
          matrix=$(printf "[%s]" "$(IFS=,; echo "${modules[*]}")")   
          fi

          echo "matrix=$matrix" >> $GITHUB_OUTPUT

#Checks which Terraform modules changed
#Adds them to a list
#Converts the list into a JSON matrix
#Passes it to GitHub Actions to run jobs only for changed modules



  # -------------------------------------------------
  # Terraform Job (Matrix)
  # -------------------------------------------------
  terraform:
    needs: module-changes
    if: needs.module-changes.outputs.matrix != '[]'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: ${{ fromJson(needs.module-changes.outputs.matrix) }}

    permissions:
      pull-requests: write
      contents: read

    defaults:
      run:
        working-directory: ./tf-resouces/${{ matrix.module }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -no-color

      - name: Post Plan to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          PLAN_DATA: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const plan = process.env.PLAN_DATA;

            const output = `#### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`terraform
            ${plan}
            \`\`\`

            </details>

            *Actor: @${context.actor}*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: apply
        run: terraform apply -auto-approve -no-color

      - name: Post Apply Results to PR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        env:
          APPLY_OUT: "${{ steps.apply.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });

            const prNumber = result.data.length > 0 ? result.data[0].number : null;

            if (prNumber) {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `### ✅ Terraform Apply Successful

                <details><summary>Show Apply Output</summary>

                \`\`\`terraform
                ${process.env.APPLY_OUT}
                \`\`\`

                </details>`
              });
            }